/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ovs;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author blest
 */
public class RegisterVote extends javax.swing.JFrame {
    /**
     * Creates new form RegisterVote
     */
    public RegisterVote() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        candidate2_selector = new javax.swing.JComboBox<>();
        ch4lbl = new javax.swing.JLabel();
        submit_vote = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ch1lbl = new javax.swing.JLabel();
        ch2 = new javax.swing.JLabel();
        ch4 = new javax.swing.JLabel();
        candidate1_selector = new javax.swing.JComboBox<>();
        candidate4_selector = new javax.swing.JComboBox<>();
        candidate3_selector = new javax.swing.JComboBox<>();
        confirm_id = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        candidate2_selector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Isaac", "2 Harry", "3 Alex", "4 Charles" }));
        candidate2_selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidate2_selectorActionPerformed(evt);
            }
        });

        ch4lbl.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        ch4lbl.setText("   4th Rank:   ");

        submit_vote.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        submit_vote.setForeground(new java.awt.Color(249, 1, 1));
        submit_vote.setText("Submit ");
        submit_vote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    submit_voteActionPerformed(evt);
                } catch (SQLException exp) {
                    System.out.println(exp);
                }
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        jLabel2.setText("Your preference list:   ");

        ch1lbl.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        ch1lbl.setText("    1st Rank:   ");

        ch2.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        ch2.setText("    2nd Rank:   ");

        ch4.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        ch4.setText("   3rd Rank:   ");

        candidate1_selector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Isaac", "2 Harry", "3 Alex", "4 Charles" }));
        candidate1_selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidate1_selectorActionPerformed(evt);
            }
        });

        candidate4_selector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Isaac", "2 Harry", "3 Alex", "4 Charles" }));
        candidate4_selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidate4_selectorActionPerformed(evt);
            }
        });

        candidate3_selector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Isaac", "2 Harry", "3 Alex", "4 Charles" }));
        candidate3_selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidate3_selectorActionPerformed(evt);
            }
        });

        confirm_id.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        confirm_id.setText("Confirm your ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ch1lbl)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(candidate2_selector, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(candidate1_selector, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(candidate4_selector, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(candidate3_selector, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ch4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(ch4lbl))
                                .addComponent(ch2)))
                        .addGap(332, 332, 332)))
                .addGap(147, 147, 147))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(confirm_id, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submit_vote, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ch1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(candidate1_selector, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(candidate2_selector, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(candidate3_selector, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ch2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ch4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ch4lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(candidate4_selector, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submit_vote, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirm_id))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void candidate2_selectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidate2_selectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_candidate2_selectorActionPerformed

    private void submit_voteActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_submit_voteActionPerformed
        String[] choices = {"flxvvcxr" + candidate1_selector.getSelectedItem().toString().charAt(0) + "u", "flxvvcxr" + candidate2_selector.getSelectedItem().toString().charAt(0) + "u",
                            "flxvvcxr" + candidate3_selector.getSelectedItem().toString().charAt(0) + "u", "flxvvcxr" + candidate4_selector.getSelectedItem().toString().charAt(0) + "u"
                           };
        String id = confirm_id.getText();
        Connection connect = null;
        Statement stmnt = null; 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            connect = DriverManager.getConnection("jdbc:mysql://localhost/ovs", "root", "saud");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        Cryptography encrypt = new Cryptography();
        stmnt = connect.createStatement();
        
        for (int i = 0; i < 4; i++) {
            System.out.println("UPDATE voter SET choice" + (i + 1) + " = '" + choices[i] + "' WHERE id = '" + encrypt.cipher(id) + "';");
            int ret = stmnt.executeUpdate("UPDATE voter SET choice" + (i + 1) + " = '" + choices[i] + "' WHERE id = '" + encrypt.cipher(id) + "';");
            System.out.println(ret);
        }
        
        int ret = stmnt.executeUpdate("Update voter SET cast_status = 1 WHERE id = '" + encrypt.cipher(id) + "';");
        System.out.println(ret);

        participantFrame participantFrame = new participantFrame();
        participantFrame.show();
        dispose();

    }//GEN-LAST:event_submit_voteActionPerformed

    private void candidate1_selectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidate1_selectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_candidate1_selectorActionPerformed

    private void candidate4_selectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidate4_selectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_candidate4_selectorActionPerformed

    private void candidate3_selectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidate3_selectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_candidate3_selectorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterVote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterVote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterVote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterVote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterVote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> candidate1_selector;
    private javax.swing.JComboBox<String> candidate2_selector;
    private javax.swing.JComboBox<String> candidate3_selector;
    private javax.swing.JComboBox<String> candidate4_selector;
    private javax.swing.JLabel ch1lbl;
    private javax.swing.JLabel ch2;
    private javax.swing.JLabel ch4;
    private javax.swing.JLabel ch4lbl;
    private javax.swing.JTextField confirm_id;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton submit_vote;
    // End of variables declaration//GEN-END:variables
}
